[2023-06-28T05:39:47.030+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_pageviews.send_email_notification scheduled__2023-06-28T04:00:00+00:00 [queued]>
[2023-06-28T05:39:47.036+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_pageviews.send_email_notification scheduled__2023-06-28T04:00:00+00:00 [queued]>
[2023-06-28T05:39:47.036+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T05:39:47.036+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-28T05:39:47.036+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T05:39:47.046+0000] {taskinstance.py:1304} INFO - Executing <Task(EmailOperator): send_email_notification> on 2023-06-28 04:00:00+00:00
[2023-06-28T05:39:47.053+0000] {standard_task_runner.py:55} INFO - Started process 187 to run task
[2023-06-28T05:39:47.055+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_pageviews', 'send_email_notification', 'scheduled__2023-06-28T04:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/load_pageviews.py', '--cfg-path', '/tmp/tmpc9w23xgp']
[2023-06-28T05:39:47.056+0000] {standard_task_runner.py:83} INFO - Job 48: Subtask send_email_notification
[2023-06-28T05:39:47.102+0000] {task_command.py:389} INFO - Running <TaskInstance: load_pageviews.send_email_notification scheduled__2023-06-28T04:00:00+00:00 [running]> on host b7f23ecf7992
[2023-06-28T05:39:47.151+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_pageviews
AIRFLOW_CTX_TASK_ID=send_email_notification
AIRFLOW_CTX_EXECUTION_DATE=2023-06-28T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-28T04:00:00+00:00
[2023-06-28T05:39:47.157+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-06-28T05:39:47.157+0000] {configuration.py:635} WARNING - section/key [smtp/smtp_user] not found in config
[2023-06-28T05:39:47.157+0000] {email.py:229} INFO - Email alerting: attempt 1
[2023-06-28T05:39:47.158+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-06-28T05:39:47.163+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=load_pageviews, task_id=send_email_notification, execution_date=20230628T040000, start_date=20230628T053947, end_date=20230628T053947
[2023-06-28T05:39:47.172+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 48 for task send_email_notification ([Errno 99] Cannot assign requested address; 187)
[2023-06-28T05:39:47.187+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-28T05:39:47.199+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
